# Generated by Django 5.0.4 on 2024-09-15 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('id_ajuste', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ajustes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Averias',
            fields=[
                ('id_averia', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Averias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nit', models.DecimalField(db_column='Nit', decimal_places=2, max_digits=10, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'Clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('total_factura', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('id_compra', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('nfactura', models.IntegerField(db_column='Nfactura', primary_key=True, serialize=False)),
                ('fecha_facturacion', models.DateField()),
                ('total_factura', models.FloatField()),
                ('id_orden_field', models.IntegerField(db_column='id_orden ')),
                ('cliente', models.IntegerField()),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'Facturas ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cod_inventario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('tipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.TextField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Remisiones',
            fields=[
                ('nremision', models.IntegerField(db_column='Nremision', primary_key=True, serialize=False)),
                ('fecha_remision', models.DateField()),
                ('total_remision', models.FloatField()),
                ('id_orden', models.IntegerField()),
                ('cliente', models.IntegerField()),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'Remisiones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('id_factura', models.IntegerField()),
                ('id_remi', models.IntegerField()),
            ],
            options={
                'db_table': 'Ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('nit', models.ForeignKey(db_column='Nit', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.clientes')),
            ],
            options={
                'db_table': 'Orden_produccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProduccionSalidasmporden',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_salida', models.DateField()),
                ('cod_inventario', models.ForeignKey(db_column='cod_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.inventario')),
            ],
            options={
                'db_table': 'produccion_salidasmporden',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.proveedores'),
        ),
        migrations.CreateModel(
            name='SalidasMpOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_e_produccion', models.DateField(blank=True, db_column='fecha_E_produccion', null=True)),
                ('cod_inventario', models.ForeignKey(db_column='cod_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.inventario')),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.ordenproduccion')),
            ],
            options={
                'db_table': 'Salidas_Mp_Orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ajuste', models.DateField()),
                ('cant_ajuste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cod_inventario', models.ForeignKey(db_column='cod_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.inventario')),
                ('id_ajuste', models.ForeignKey(db_column='id_ajuste', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.ajustes')),
            ],
            options={
                'db_table': 'Transaccion_ajuste',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionAverias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_averia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_averia', models.DateField()),
                ('cod_inventario', models.ForeignKey(db_column='cod_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.inventario')),
                ('id_averia', models.ForeignKey(db_column='id_averia', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.averias')),
            ],
            options={
                'db_table': 'Transaccion_averias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_inventario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha_factura', models.DateField()),
                ('precio_venta', models.FloatField()),
                ('nfactura', models.ForeignKey(db_column='Nfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.facturas')),
            ],
            options={
                'db_table': 'Transaccion_Factura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(db_column='fecha_Entrega')),
                ('estado', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('prioridad', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('responsable', models.TextField()),
                ('fecha_terminacion_orden', models.DateField(blank=True, null=True)),
                ('cod_inventario', models.ForeignKey(db_column='cod_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.inventario')),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.ordenproduccion')),
            ],
            options={
                'db_table': 'Transaccion_orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_inventario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha_remision', models.DateField()),
                ('precio_venta', models.FloatField()),
                ('nremision', models.ForeignKey(db_column='Nremision', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.remisiones')),
            ],
            options={
                'db_table': 'Transaccion_Remision',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transformulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('materia1', models.IntegerField(blank=True, null=True)),
                ('cant_materia1', models.FloatField(blank=True, null=True)),
                ('materia2', models.IntegerField(blank=True, null=True)),
                ('cant_materia2', models.FloatField(blank=True, null=True)),
                ('materia3', models.IntegerField(blank=True, null=True)),
                ('cant_materia3', models.FloatField(blank=True, null=True)),
                ('materia4', models.IntegerField(blank=True, null=True)),
                ('cant_materia4', models.FloatField(blank=True, null=True)),
                ('materia5', models.IntegerField(blank=True, null=True)),
                ('cant_materia5', models.FloatField(blank=True, null=True)),
                ('materia6', models.IntegerField(blank=True, null=True)),
                ('cant_materia6', models.FloatField(blank=True, null=True)),
                ('materia7', models.IntegerField(blank=True, null=True)),
                ('cant_materia7', models.FloatField(blank=True, null=True)),
                ('materia8', models.IntegerField(blank=True, null=True)),
                ('cant_materia8', models.FloatField(blank=True, null=True)),
                ('porcentajeiva', models.FloatField()),
                ('pocentajeutilidad', models.FloatField()),
                ('costosindirectos', models.FloatField()),
                ('cod_inventario', models.ForeignKey(db_column='cod_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.inventario')),
            ],
            options={
                'db_table': 'transformulas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransMp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mp', models.TextField()),
                ('cant_mp', models.IntegerField()),
                ('costo_unitario', models.FloatField()),
                ('total_linea', models.FloatField()),
                ('fecha_ingreso', models.DateField()),
                ('unidad_medida', models.TextField()),
                ('id_proveedor', models.IntegerField()),
                ('tipo', models.TextField(blank=True, null=True)),
                ('cod_inventario', models.ForeignKey(db_column='cod_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.inventario')),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.compras')),
            ],
            options={
                'db_table': 'trans_mp',
                'managed': True,
            },
        ),
    ]
