# Generated by Django 5.0.4 on 2024-10-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nit',
            field=models.BigIntegerField(db_column='Nit', primary_key=True, serialize=False),
        ),
    ]
