# Generated by Django 5.0.4 on 2024-11-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformulas',
            name='cant_materia10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformulas',
            name='cant_materia9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformulas',
            name='materia10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformulas',
            name='materia9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
