# Generated by Django 5.0.4 on 2024-11-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_transformulas_cant_materia10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionaverias',
            name='motivo',
            field=models.CharField(default='Envase Roto', max_length=255),
        ),
    ]
