# Generated by Django 5.0.4 on 2024-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_transaccionaverias_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='ica',
            field=models.BooleanField(default=False),
        ),
    ]
