# Generated by Django 5.0.4 on 2024-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_facturas_ica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='cliente',
            field=models.BigIntegerField(),
        ),
    ]
