# Generated by Django 5.0.4 on 2024-11-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_facturas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionorden',
            name='etiquetado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaccionorden',
            name='responsables',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaccionorden',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
