# Generated by Django 5.0.4 on 2024-11-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_transaccionorden_etiquetado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformulas',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
