# Generated by Django 5.0.4 on 2024-12-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_alter_inventario_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidasmporden',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
