# Generated by Django 5.0.4 on 2024-12-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_alter_salidasmporden_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionorden',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
