# Generated by Django 5.0.4 on 2024-12-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_alter_transaccionorden_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionfactura',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaccionremision',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
