# Generated by Django 5.0.4 on 2025-01-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_alter_transaccionfactura_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionorden',
            name='prioridadItem',
            field=models.BooleanField(default=False),
        ),
    ]
