# Generated by Django 5.0.4 on 2025-02-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_transaccionorden_prioridaditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_min', models.FloatField(default=0)),
                ('cod_inventario', models.ForeignKey(db_column='cod_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.inventario')),
            ],
            options={
                'db_table': 'alerta_productos',
                'managed': True,
            },
        ),
    ]
