# Generated by Django 5.0.4 on 2025-02-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_productosalerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasosSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=20)),
                ('fechaCaso', models.DateField()),
                ('decripcionCaso', models.TextField()),
                ('tipoCaso', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'casos_soporte',
                'managed': True,
            },
        ),
    ]
