# Generated by Django 5.0.4 on 2025-02-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_casossoporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casossoporte',
            old_name='decripcionCaso',
            new_name='descripcionCaso',
        ),
    ]
