# Generated by Django 5.0.4 on 2025-02-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_rename_decripcioncaso_casossoporte_descripcioncaso'),
    ]

    operations = [
        migrations.AddField(
            model_name='casossoporte',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
