# Generated by Django 5.0.4 on 2025-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_casossoporte_resuelto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListadoPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtabla', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('fecha_actualizacion', models.DateField()),
            ],
            options={
                'db_table': 'listado_precios',
                'managed': True,
            },
        ),
    ]
